# Enable C++ support
language: cpp
notifications:
  email: false

addons:
  apt:
    packages:
      - cmake
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
  homebrew:
    packages:
      - cmake
      - sdl2
      - sdl2_image
      - sdl2_ttf
      - sdl2_mixer

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=../install
  - cmake --build . --target install

matrix:
  include:
    - name: "Linux gcc"
      os: linux
      dist: xenial
      compiler: gcc
    - name: "Linux clang"
      os: linux
      dist: xenial
      compiler: clang
    - name: "MacOS clang"
      os: osx
      osx_image: xcode10.2
      compiler: clang
