version: '{branch}.{build}'
image: Visual Studio 2017
clone_depth: 1
platform: x64
cache:
  - c:\usr

before_build:
  - |-
    set PREFIX=C:\usr
    set ARCH=x64

  # depends are only fetched where there's no cache
  - if exist %PREFIX% set DEPENDS=rem

  - |-
    %DEPENDS% mkdir %PREFIX%\include
    %DEPENDS% mkdir %PREFIX%\lib
    %DEPENDS% cd %TEMP%
  # SDL2
  - |-
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip
    %DEPENDS% 7z x SDL2-devel-2.0.10-VC.zip > nul
    %DEPENDS% copy SDL2-2.0.10\include\* %PREFIX%\include > nul
    %DEPENDS% copy SDL2-2.0.10\lib\%ARCH%\*.lib %PREFIX%\lib > nul
    %DEPENDS% copy SDL2-2.0.10\lib\%ARCH%\*.dll %PREFIX%\lib > nul
  # SDL2_image
  - |-
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
    %DEPENDS% 7z x SDL2_image-devel-2.0.5-VC.zip > nul
    %DEPENDS% copy SDL2_image-2.0.5\include\* %PREFIX%\include > nul
    %DEPENDS% copy SDL2_image-2.0.5\lib\%ARCH%\*.lib %PREFIX%\lib > nul
    %DEPENDS% copy SDL2_image-2.0.5\lib\%ARCH%\*.dll %PREFIX%\lib > nul
  # SDL2_ttf
  - |-
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip
    %DEPENDS% 7z x SDL2_ttf-devel-2.0.15-VC.zip > nul
    %DEPENDS% copy SDL2_ttf-2.0.15\include\* %PREFIX%\include > nul
    %DEPENDS% copy SDL2_ttf-2.0.15\lib\%ARCH%\*.lib %PREFIX%\lib > nul
    %DEPENDS% copy SDL2_ttf-2.0.15\lib\%ARCH%\*.dll %PREFIX%\lib > nul

build_script:
- cmd: >-
    md build && cd build
    cmake -G "Visual Studio 15 2017" ..
    cd ..
    cmake --build build --target install
